blank_issues_enabled: true
contact_links:
  - name: 📚 Documentation
    url: https://github.com/chillwhales/marketplace/tree/main/apps/web/docs
    about: Check the project documentation
  - name: 💬 Discussions
    url: https://github.com/chillwhales/marketplace/discussions
    about: Ask questions and discuss ideas
